image: ruby:2.3

stages:
  - build
  - deploy

cache:
  paths:
  - vendor

build:
  stage: build
  script:
  - apt-get update -yqqq
  - apt-get install -y nodejs
  - bundle install --path vendor
  - bundle exec middleman build
  artifacts:
    paths:
    - build

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - apt-get update -yqqq
    - apt-get install -y nodejs
    - bundle install --path vendor
    - bundle exec middleman build -e staging
    - pip install awscli
    - aws s3 rm s3://staging.localhost.events --recursive
    - aws s3 sync build s3://staging.localhost.events --acl public-read --cache-control "public, max-age=86400"
  environment:
    name: staging
    url: http://staging.localhost.events.s3-website-ap-southeast-2.amazonaws.com
  only:
  - staging

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
    - pip install awscli
  environment:
    name: production
    url: https://localhost.events
  when: manual
  only:
  - master
